package interfaz;

import dominio.Sistema;
import dominio.modelo.Animal;
import dominio.modelo.personas.Adoptante;
import dominio.modelo.personas.Responsable;
import dominio.modelo.personas.Padrino;
import dominio.tools.Moneda;
import dominio.tools.Pago;
import dominio.tools.Periodo;
import interfaz.paneles.*;
import javax.swing.ImageIcon;

public class MainWindow extends javax.swing.JFrame {

    Sistema sistema = Sistema.getInstance();

    public MainWindow() {
        Animal a1 = new Animal("Nombre1", "tipo1", 120, 5000, "Comentario1");
        Animal a2 = new Animal("Nombre2", "tipo2", 120, 5000, "Comentario2");
        Animal a3 = new Animal("Nombre3", "tipo3", 120, 5000, "Comentario3");
        Animal a4 = new Animal("Nombre4", "tipo4", 120, 5000, "Comentario4");
        Animal a5 = new Animal("Nombre5", "tipo5", 120, 5000, "Comentario5");
        Animal a6 = new Animal("Nombre6", "tipo6", 120, 5000, "Comentario6");
        Animal a7 = new Animal("Nombre7", "tipo7", 120, 5000, "Comentario7");
        Animal a8 = new Animal("Nombre8", "tipo8", 120, 5000, "Comentario8");
        Animal a9 = new Animal("Nombre9", "tipo9", 120, 5000, "Comentario9");
        Animal a10 = new Animal("Nombre10", "tipo10", 120, 5000, "Comentario10");

        sistema.addAnimal(a1);
        sistema.addAnimal(a2);
        sistema.addAnimal(a3);
        sistema.addAnimal(a4);
        sistema.addAnimal(a5);
        sistema.addAnimal(a6);
        sistema.addAnimal(a7);
        sistema.addAnimal(a8);
        sistema.addAnimal(a9);
        sistema.addAnimal(a10);

        Responsable r1 = new Responsable("Nombre1", "Apellido1", "email1");
        Responsable r2 = new Responsable("Nombre2", "Apellido2", "email2");
        Responsable r3 = new Responsable("Nombre3", "Apellido3", "email3");

        Adoptante ad1 = new Adoptante("Nombre4", "Apellido4", "email4", "tel4");
        Adoptante ad2 = new Adoptante("Nombre5", "Apellido5", "email5", "tel5");
        Adoptante ad3 = new Adoptante("Nombre6", "Apellido6", "email6", "tel6");

        Padrino p1 = new Padrino("Nombre7", "Apellido7", "email7", "telefono7", "Ciudad7", "Pais7", Pago.NO_ESPECIFICADO, Periodo.NO_ESPECIFICADO, Moneda.NO_ESPECIFICADA, 7);
        Padrino p2 = new Padrino("Nombre8", "Apellido8", "email8", "telefono8", "Ciudad8", "Pais8", Pago.NO_ESPECIFICADO, Periodo.NO_ESPECIFICADO, Moneda.NO_ESPECIFICADA, 8);
        Padrino p3 = new Padrino("Nombre9", "Apellido9", "email9", "telefono9", "Ciudad9", "Pais9", Pago.NO_ESPECIFICADO, Periodo.NO_ESPECIFICADO, Moneda.NO_ESPECIFICADA, 9);
        try {
            sistema.addResponsable(r1);
            sistema.addResponsable(r2);
            sistema.addResponsable(r3);

            sistema.addAdoptante(ad1);
            sistema.addAdoptante(ad2);
            sistema.addAdoptante(ad3);

            sistema.addPadrino(p1);
            sistema.addPadrino(p2);
            sistema.addPadrino(p3);
        } catch (Exception ex) {
        }

        initComponents();

        Calendario pCal = new Calendario();
        Animales pAnim = new Animales();
        Veterinarias pVeter = new Veterinarias();
        Personas pPers = new Personas();

        jTabbedPane1.addTab("Calendario", new ImageIcon(getClass().getResource("/interfaz/Resources/icons8-calendar-32.png")), pCal);
        jTabbedPane1.addTab("Animales", new ImageIcon(getClass().getResource("/interfaz/Resources/icons8-dog-32.png")), pAnim);
        jTabbedPane1.addTab("Veterinarias", new ImageIcon(getClass().getResource("/interfaz/Resources/icons8-veterinarian-32.png")), pVeter);
        jTabbedPane1.addTab("Personas", new ImageIcon(getClass().getResource("/interfaz/Resources/icons8-people-32.png")), pPers);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Calendario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
